version: "3.8"
services:
  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: api
    build:
      context: ./backend
      args:
        DATABASE_URL: ${DATABASE_URL}
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  postgres-data: